### PR TITLE
Fix breaking FormsFX changes

### PR DESCRIPTION
**Pull request by martinfrancois**
Since FormsFX 1.3.0, because of https://github.com/dlemmermann/formsfx/pull/28 there is no longer a call to `getFields()`, which was replaced to a call to `getElements()` instead. Also, a concept of `Element`s was introduced, which `Field` now extends. The missing call caused a breaking change, since in our own implementation of a renderer, we used said call.

This fix is not ideal, since it casts the `Element`s we get from `getElement()` to a `Field`, which means if someone would want to define an `Element`, it would throw a `ClassCastException`. However, it is a good tradeoff, since we currently only support `Field` anyways and changing `PreferencesFX` to consistently use `Element` instead is a quite major refactoring, as almost all classes use `Field` in some form, especially including our custom renderers.

### CODE REVIEW

**Comment by dlemmermann** [comment]
But aren't those elements things like additional text for describing a field? I know that @aalmiray added some functionality for this in FormsFX. Was he planning on also using it in PreferencesFX?

**Comment by martinfrancois** [comment]
@dlemmermann could be, but in this case I would suggest to add the `Element` functionality at a later point to the API.

**Comment by aalmiray** [comment]
Indeed. `Element` is required in order to render additional content related to a `Field`. This is part of the possible enhancements that can be added to PreferencesFX.

**Comment by dlemmermann** [comment]
OK, but this has to be done in a later release then. For now PreferencesFX will only support Fields. I have asked the team to submit an enhancement ticket for the new features.

**Pull request merged**
