### PR TITLE
ColorPicker preference

### PR DESCRIPTION
**Pull request by ArvidNy**
I've created a ColorPicker preference and a DirectoryChooser preference based on the SimpleTextControl class that we need for our project. 

This is what you do to use them:
```
StringProperty colorProperty = new SimpleStringProperty(Color.BLACK.toString());
StringField colorField = Field.ofStringType(colorProperty).render(
                new SimpleColorPickerControl(Color.BLACK));

Setting.of("Set color", colorField, colorProperty);

StringProperty directoryProperty = new SimpleStringProperty();
StringField directoryField = Field.ofStringType(directoryProperty).render(
                new SimpleDirectoryChooserControl(primaryStage, "Browse", null));

Setting.of("Select path", directoryField, directoryProperty);
```

This is probably not an ideal solution, but it works for me. I'm just going to leave this PR as is since I won't be able to do any more programming for a while. Feel free to make any changes/improvements to the code as you like. If there's any questions, just ask and I'll try to answer as I find the time.

### CODE REVIEW

**Comment by Rykee** [comment]
How would I get the stage of the preferences before calling show?

**Comment by ArvidNy** [comment]
I believe it's not really possible without heavily modifying the main code, given that you need to create the setting before creating the preferences window. I've used the Stage from my main JavaFX program and that works well enough for me. If you don't have another windowOwner you would like to add, you could always pass a null value instead.

**Comment by ArvidNy** [comment]
Sorry, scratch that! I just gave it another thought and I realized that you could always change line 106 in `SimpleDirectoryChooserControl` to this instead:
```
File dir = directoryChooser.showDialog(getNode().getScene().getWindow());
```
That should give you the result you are looking for.

**Comment by Genron** [comment]
Hi, @ArvidNy Finally we had time to review your pull request. It is really great and those are two really cool components, which we woud like to add to our framework. However, we'd like to ask you for two things:
- Please remove the directory chooser part from this pull request, as the color control is now ready to be merged
- Please put the directory chooser part into a separate branch, and we would like to not only have a directory chooser, but a file chooser as well, so we can cover both cases. Then, create a new pull request for that so we can have a look at that separately.
Would that be possible for you?

**Comment by ArvidNy** [comment]
Sure, I'll split them into two branches right away and let you know when I'm done. I won't have time to make any additions to the directory chooser, but I'll create the PR for you to make any changes you want.

**Comment by ArvidNy** [comment]
This should now be sorted out. Thanks for the review and for a great project!

**Pull request merged**
